# Generated by Django 6.0 on 2025-12-31 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("status", "Status Report"),
                            ("standup", "Standup"),
                            ("summary", "Summary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("rendered_text", models.TextField(blank=True)),
                ("rendered_html", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "-created_at"],
                        name="reporting_r_user_id_4a0431_idx",
                    ),
                    models.Index(
                        fields=["kind", "-created_at"], name="reporting_r_kind_2f0417_idx"
                    ),
                ],
            },
        ),
    ]
