/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChatInput: typeof import('./src/components/AIChatInput.vue')['default']
    AuthLogo: typeof import('./src/components/AuthLogo.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next/components/BCard')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownHeader: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownHeader']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormText: typeof import('bootstrap-vue-next/components/BForm')['BFormText']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    ChoicesInput: typeof import('./src/components/ChoicesInput.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    CustomApexChart: typeof import('./src/components/CustomApexChart.vue')['default']
    CustomEChart: typeof import('./src/components/CustomEChart.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    PageBreadcrumb: typeof import('./src/components/PageBreadcrumb.vue')['default']
    PasswordStrengthBar: typeof import('./src/components/PasswordStrengthBar.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    TanstackTable: typeof import('./src/components/TanstackTable.vue')['default']
    TextDifferentView: typeof import('./src/components/TextDifferentView.vue')['default']
    TouchSpinInput: typeof import('./src/components/TouchSpinInput.vue')['default']
    UICard: typeof import('./src/components/UICard.vue')['default']
  }
}
