# Generated by Django 6.0.1 on 2026-01-18 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitePasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Hashed passkey', max_length=64, unique=True)),
                ('raw_key', models.CharField(blank=True, help_text='Plain text key shown once at creation', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time', null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times this passkey can be used')),
                ('actual_uses', models.IntegerField(default=0, help_text='Number of times actually used')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this passkey')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passkeys', to=settings.AUTH_USER_MODEL)),
                ('tenant_scope', models.ForeignKey(blank=True, help_text='If set, limits signup to this tenant', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Passkey',
                'verbose_name_plural': 'Invite Passkeys',
                'db_table': 'invitations_passkey',
                'ordering': ['-created_at'],
            },
        ),
    ]
