# Generated by Django 6.0.1 on 2026-01-18 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('tenants', '0001_initial'),
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_ai_context', models.BooleanField(default=True, help_text='Allow this document to be used as AI context')),
                ('allow_indexing', models.BooleanField(default=True, help_text='Allow this document to be indexed for search')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='artifacts.artifact')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_privacy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Privacy Setting',
                'verbose_name_plural': 'Document Privacy Settings',
                'db_table': 'system_document_privacy',
            },
        ),
        migrations.CreateModel(
            name='EntryPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_ai_context', models.BooleanField(default=True, help_text='Allow this entry to be used as AI context')),
                ('exclude_from_exports', models.BooleanField(default=False, help_text='Exclude from data exports')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_privacy_updates', to=settings.AUTH_USER_MODEL)),
                ('worklog_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='worklog.worklog')),
            ],
            options={
                'verbose_name': 'Entry Privacy Setting',
                'verbose_name_plural': 'Entry Privacy Settings',
                'db_table': 'system_entry_privacy',
            },
        ),
        migrations.CreateModel(
            name='MetricsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_spike_threshold_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Alert if churn increases by this %', max_digits=5)),
                ('payment_failure_threshold', models.IntegerField(default=5, help_text='Alert if failures exceed this count')),
                ('error_rate_threshold_pct', models.DecimalField(decimal_places=2, default=5.0, help_text='Alert if error rate exceeds this %', max_digits=5)),
                ('job_failure_threshold_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Alert if job failure rate exceeds this %', max_digits=5)),
                ('monthly_burn_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly cash burn (manual input)', max_digits=12, null=True)),
                ('runway_months', models.IntegerField(blank=True, help_text='Months of runway (manual input)', null=True)),
                ('enable_stripe_metrics', models.BooleanField(default=False)),
                ('enable_ai_cost_tracking', models.BooleanField(default=True)),
                ('enable_cohort_analysis', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_metrics_config',
            },
        ),
        migrations.CreateModel(
            name='ActivationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('file_upload', 'File Upload'), ('worklog_create', 'Worklog Created'), ('report_generate', 'Report Generated'), ('skill_compute', 'Skills Computed'), ('login', 'Login')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_activation_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='system_acti_user_id_401675_idx'), models.Index(fields=['tenant', 'event_type', '-timestamp'], name='system_acti_tenant__975c23_idx')],
            },
        ),
        migrations.CreateModel(
            name='CohortRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_month', models.DateField(help_text='First day of signup month')),
                ('cohort_size', models.IntegerField(default=0, help_text='Users in this cohort')),
                ('week_1_retained', models.IntegerField(default=0)),
                ('week_4_retained', models.IntegerField(default=0)),
                ('week_12_retained', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_cohort_retention',
                'ordering': ['-cohort_month'],
                'unique_together': {('cohort_month', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='MetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('bucket_date', models.DateField(db_index=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(db_index=True, default='production', max_length=20)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Recurring Revenue', max_digits=12, null=True)),
                ('arr', models.DecimalField(blank=True, decimal_places=2, help_text='Annual Recurring Revenue (MRR * 12)', max_digits=12, null=True)),
                ('nrr', models.DecimalField(blank=True, decimal_places=2, help_text='Net Revenue Retention %', max_digits=6, null=True)),
                ('grr', models.DecimalField(blank=True, decimal_places=2, help_text='Gross Revenue Retention %', max_digits=6, null=True)),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('churned_customers', models.IntegerField(default=0)),
                ('reactivated_customers', models.IntegerField(default=0)),
                ('customer_churn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('revenue_churn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('signups_total', models.IntegerField(default=0)),
                ('activated_users', models.IntegerField(default=0, help_text='Users who completed key actions')),
                ('trial_started', models.IntegerField(default=0)),
                ('trial_converted', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0, help_text='Daily Active Users')),
                ('wau', models.IntegerField(default=0, help_text='Weekly Active Users')),
                ('mau', models.IntegerField(default=0, help_text='Monthly Active Users')),
                ('users_uploaded_file', models.IntegerField(default=0)),
                ('users_created_worklog', models.IntegerField(default=0)),
                ('users_generated_report', models.IntegerField(default=0)),
                ('stripe_active_subscriptions', models.IntegerField(blank=True, null=True)),
                ('stripe_past_due', models.IntegerField(blank=True, null=True)),
                ('stripe_canceled', models.IntegerField(blank=True, null=True)),
                ('stripe_failed_payments', models.IntegerField(blank=True, null=True)),
                ('api_requests_total', models.IntegerField(default=0)),
                ('api_errors_total', models.IntegerField(default=0)),
                ('api_avg_latency_ms', models.IntegerField(blank=True, null=True)),
                ('jobs_total', models.IntegerField(default=0)),
                ('jobs_succeeded', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('jobs_avg_duration_sec', models.IntegerField(blank=True, null=True)),
                ('ai_tokens_used', models.BigIntegerField(default=0)),
                ('ai_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cash_burn_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('runway_months', models.IntegerField(blank=True, null=True)),
                ('outstanding_invoices_count', models.IntegerField(blank=True, null=True)),
                ('outstanding_invoices_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for global/all-tenants metrics', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_metrics_snapshot',
                'ordering': ['-bucket_date', '-computed_at'],
                'indexes': [models.Index(fields=['-bucket_date', 'tenant'], name='system_metr_bucket__04555b_idx'), models.Index(fields=['bucket_type', 'environment'], name='system_metr_bucket__3232bd_idx')],
                'unique_together': {('bucket_type', 'bucket_date', 'tenant', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('ai_context', 'Use data as AI context'), ('analytics', 'Usage analytics'), ('product_improvements', 'Product improvements'), ('marketing', 'Marketing communications')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_privacy_consent',
                'indexes': [models.Index(fields=['user', 'tenant', 'consent_type'], name='system_priv_user_id_2bf352_idx'), models.Index(fields=['tenant', 'consent_type', 'granted'], name='system_priv_tenant__b3f979_idx')],
                'unique_together': {('user', 'tenant', 'consent_type')},
            },
        ),
    ]
