# Generated by Django 5.2.9 on 2025-12-31 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('system', '0001_initial'),
        ('tenants', '0002_tenant_plan_tenant_settings_tenantmembership'),
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_ai_context', models.BooleanField(default=True, help_text='Allow this document to be used as AI context')),
                ('allow_indexing', models.BooleanField(default=True, help_text='Allow this document to be indexed for search')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='artifacts.artifact')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_privacy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Privacy Setting',
                'verbose_name_plural': 'Document Privacy Settings',
                'db_table': 'system_document_privacy',
            },
        ),
        migrations.CreateModel(
            name='EntryPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_ai_context', models.BooleanField(default=True, help_text='Allow this entry to be used as AI context')),
                ('exclude_from_exports', models.BooleanField(default=False, help_text='Exclude from data exports')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_privacy_updates', to=settings.AUTH_USER_MODEL)),
                ('worklog_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='worklog.worklog')),
            ],
            options={
                'verbose_name': 'Entry Privacy Setting',
                'verbose_name_plural': 'Entry Privacy Settings',
                'db_table': 'system_entry_privacy',
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('ai_context', 'Use data as AI context'), ('analytics', 'Usage analytics'), ('product_improvements', 'Product improvements'), ('marketing', 'Marketing communications')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_privacy_consent',
                'indexes': [models.Index(fields=['user', 'tenant', 'consent_type'], name='system_priv_user_id_2bf352_idx'), models.Index(fields=['tenant', 'consent_type', 'granted'], name='system_priv_tenant__b3f979_idx')],
                'unique_together': {('user', 'tenant', 'consent_type')},
            },
        ),
    ]
