# Generated by Django 6.0 on 2025-12-31 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Rates 2024', max_length=100)),
                ('plan_tier', models.CharField(help_text='free, starter, professional, enterprise', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'db_table': 'billing_rate_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='e.g., checkout.session.completed', max_length=100)),
                ('payload_hash', models.CharField(help_text='SHA256 hash of event payload', max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_result', models.CharField(default='success', help_text='success, failed, skipped', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('tenant_id', models.IntegerField(blank=True, help_text='Resolved tenant ID', null=True)),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
                'db_table': 'billing_stripe_event',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True, unique=True)),
                ('plan_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, help_text='active, past_due, canceled, etc.', max_length=50, null=True)),
                ('subscription_current_period_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_current_period_end', models.DateTimeField(blank=True, null=True)),
                ('allow_portal_access', models.BooleanField(default=True)),
                ('allow_plan_changes', models.BooleanField(default=True)),
                ('allow_cancellation', models.BooleanField(default=True)),
                ('auto_topup_enabled', models.BooleanField(default=False)),
                ('auto_topup_threshold_cents', models.IntegerField(default=1000, help_text='Trigger auto top-up when balance below this (cents)')),
                ('auto_topup_amount_cents', models.IntegerField(default=5000, help_text='Amount to add when auto top-up triggers (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Billing Profile',
                'verbose_name_plural': 'Billing Profiles',
                'db_table': 'billing_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Incrementing version number')),
                ('effective_from', models.DateTimeField(help_text='When this version becomes active')),
                ('effective_to', models.DateTimeField(blank=True, help_text='When this version expires (null = current)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='billing.ratecard')),
            ],
            options={
                'verbose_name': 'Rate Card Version',
                'verbose_name_plural': 'Rate Card Versions',
                'db_table': 'billing_rate_card_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('prompt_tokens', 'Prompt Tokens'), ('completion_tokens', 'Completion Tokens'), ('embedding_tokens', 'Embedding Tokens'), ('per_request', 'Per API Request'), ('per_mb_storage', 'Per MB Storage'), ('per_job', 'Per Job Execution'), ('per_document', 'Per Document Processed')], max_length=50)),
                ('provider', models.CharField(blank=True, help_text='e.g., openai, anthropic', max_length=100)),
                ('model', models.CharField(blank=True, help_text='e.g., gpt-4, claude-3-opus', max_length=100)),
                ('price_per_unit_cents', models.DecimalField(decimal_places=6, help_text='Price in cents per unit (e.g., per 1000 tokens)', max_digits=12)),
                ('unit_size', models.IntegerField(default=1, help_text='e.g., 1000 for per-1K-tokens pricing')),
                ('description', models.TextField(blank=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.ratecardversion')),
            ],
            options={
                'verbose_name': 'Rate Line Item',
                'verbose_name_plural': 'Rate Line Items',
                'db_table': 'billing_rate_line_item',
                'ordering': ['usage_type', 'provider', 'model'],
            },
        ),
        migrations.CreateModel(
            name='ReserveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cents', models.BigIntegerField(default=0, help_text='Current balance in cents')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('low_balance_policy', models.CharField(choices=[('block', 'Block execution when insufficient funds'), ('warn', 'Warn but allow execution'), ('limited', 'Allow limited workflows only')], default='warn', max_length=20)),
                ('low_balance_threshold_cents', models.IntegerField(default=500, help_text='Threshold for low balance warnings (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_account', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reserve Account',
                'verbose_name_plural': 'Reserve Accounts',
                'db_table': 'billing_reserve_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReserveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('topup', 'Top-up Payment'), ('usage', 'Usage Deduction'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment'), ('auto_topup', 'Automatic Top-up')], max_length=20)),
                ('amount_cents', models.BigIntegerField(help_text='Positive for credits, negative for debits')),
                ('balance_after_cents', models.BigIntegerField(help_text='Balance snapshot after this entry')),
                ('related_job_id', models.CharField(blank=True, help_text='JobRun ID if usage deduction', max_length=255, null=True)),
                ('related_stripe_event_id', models.CharField(blank=True, help_text='Stripe event ID if payment-related', max_length=255, null=True)),
                ('related_usage_event_id', models.BigIntegerField(blank=True, help_text='UsageEvent ID if usage deduction', null=True)),
                ('notes', models.TextField(blank=True, help_text='Description or admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this (for adjustments)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_ledger', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reserve Ledger Entry',
                'verbose_name_plural': 'Reserve Ledger Entries',
                'db_table': 'billing_reserve_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_run_id', models.CharField(help_text='JobRun or DAG run identifier', max_length=255)),
                ('dag_name', models.CharField(blank=True, max_length=100)),
                ('tool_name', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('tokens_in', models.IntegerField(blank=True, help_text='Prompt tokens', null=True)),
                ('tokens_out', models.IntegerField(blank=True, help_text='Completion tokens', null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=2, help_text='For non-token usage (MB, documents, etc.)', max_digits=12, null=True)),
                ('usage_type', models.CharField(blank=True, help_text='per_request, per_mb_storage, etc.', max_length=50)),
                ('cost_computed', models.BooleanField(default=False)),
                ('cost_cents', models.BigIntegerField(blank=True, help_text='Computed cost in cents', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rate_version_used', models.ForeignKey(blank=True, help_text='Rate version used for cost computation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.ratecardversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'db_table': 'billing_usage_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BillingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('adjust_reserve', 'Manual Reserve Adjustment'), ('change_rate', 'Rate Card Change'), ('refund', 'Issue Refund'), ('change_policy', 'Change Balance Policy'), ('override_block', 'Override Execution Block')], max_length=50)),
                ('reason', models.TextField(help_text='Required justification for the action')),
                ('details', models.JSONField(default=dict, help_text='Structured details of the action')),
                ('affected_ledger_entry_id', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_audit_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Billing Audit Log',
                'verbose_name_plural': 'Billing Audit Logs',
                'db_table': 'billing_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='billing_aud_tenant__4a0c09_idx'), models.Index(fields=['action', '-timestamp'], name='billing_aud_action_4d705d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ratecardversion',
            index=models.Index(fields=['effective_from', 'effective_to'], name='billing_rat_effecti_7765d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratecardversion',
            unique_together={('rate_card', 'version')},
        ),
        migrations.AddIndex(
            model_name='ratelineitem',
            index=models.Index(fields=['version', 'usage_type', 'provider', 'model'], name='billing_rat_version_e4d6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reserveledgerentry',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_res_tenant__e557ff_idx'),
        ),
        migrations.AddIndex(
            model_name='reserveledgerentry',
            index=models.Index(fields=['entry_type', '-created_at'], name='billing_res_entry_t_967c69_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', '-timestamp'], name='billing_usa_tenant__9f861f_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['job_run_id'], name='billing_usa_job_run_72bfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['cost_computed', 'timestamp'], name='billing_usa_cost_co_29385d_idx'),
        ),
    ]
