# Generated by Django 6.0 on 2025-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('signup_success', 'Signup Success'), ('signup_failure', 'Signup Failure'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('passkey_validated', 'Passkey Validated'), ('passkey_consumed', 'Passkey Consumed'), ('passkey_rejected', 'Passkey Rejected'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('tenant_changed', 'Tenant Changed'), ('profile_updated', 'Profile Updated'), ('admin_action', 'Admin Action')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data')),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Auth Event',
                'verbose_name_plural': 'Auth Events',
                'db_table': 'auditing_auth_event',
                'ordering': ['-timestamp'],
            },
        ),
    ]
