# Generated by Django 6.0.1 on 2026-01-18 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('signup_success', 'Signup Success'), ('signup_failure', 'Signup Failure'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('passkey_validated', 'Passkey Validated'), ('passkey_consumed', 'Passkey Consumed'), ('passkey_rejected', 'Passkey Rejected'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('tenant_changed', 'Tenant Changed'), ('profile_updated', 'Profile Updated'), ('admin_action', 'Admin Action')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data')),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('passkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='invitations.invitepasskey')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with event (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth Event',
                'verbose_name_plural': 'Auth Events',
                'db_table': 'auditing_auth_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='auditing_au_timesta_6d2979_idx'), models.Index(fields=['user', '-timestamp'], name='auditing_au_user_id_5b0dae_idx'), models.Index(fields=['ip_address', '-timestamp'], name='auditing_au_ip_addr_99d5d8_idx')],
            },
        ),
    ]
