# Generated by Django 6.0 on 2025-12-31 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditing', '0001_initial'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='passkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='invitations.invitepasskey'),
        ),
        migrations.AddField(
            model_name='authevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with event (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['-timestamp', 'event_type'], name='auditing_au_timesta_6d2979_idx'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['user', '-timestamp'], name='auditing_au_user_id_5b0dae_idx'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['ip_address', '-timestamp'], name='auditing_au_ip_addr_99d5d8_idx'),
        ),
    ]
