# Generated by Django 6.0 on 2025-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
