# Generated by Django 6.0.1 on 2026-01-18 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='worklog.epic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, help_text='Your role on this project (optional)', max_length=200)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='worklog.client')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='epic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='worklog.project'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.TextField(blank=True, help_text='Sprint goal/objective')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='worklog.project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='worklog.feature')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='worklog.story')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('work_type', models.CharField(choices=[('delivery', 'Delivery'), ('planning', 'Planning'), ('incident', 'Incident Response'), ('support', 'Support'), ('learning', 'Learning/Training'), ('other', 'Other')], default='delivery', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for review'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('content', models.TextField(help_text='What you did (raw notes are fine).')),
                ('outcome', models.TextField(blank=True, help_text='What was accomplished / delivered.')),
                ('impact', models.TextField(blank=True, help_text='Why it mattered (metrics, customer impact, risk reduction).')),
                ('next_steps', models.TextField(blank=True, help_text='What’s next / follow-ups.')),
                ('effort_minutes', models.PositiveIntegerField(blank=True, help_text='Effort in minutes (optional).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_billable', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Keywords: skills, tech, tools, etc.')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('assistant', 'AI Assistant'), ('email', 'Email Import'), ('slack', 'Slack Import'), ('calendar', 'Calendar Import'), ('ticket', 'Ticket System Import'), ('other', 'Other')], default='manual', max_length=30)),
                ('source_ref', models.CharField(blank=True, help_text='Optional external reference id (email id, ticket id).', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured metadata.')),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('reviewed', 'Reviewed/Accepted'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('enrichment_suggestions', models.JSONField(blank=True, default=dict, help_text='Assistant suggestions (skills, bullets, summary, etc.).')),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.client')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.epic')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.feature')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.sprint')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.story')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='worklog.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('code', 'Code'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='document', max_length=20)),
                ('storage_provider', models.CharField(choices=[('minio', 'MinIO/S3'), ('local', 'Local'), ('other', 'Other')], default='minio', max_length=20)),
                ('object_key', models.CharField(help_text='Object key/path in the storage backend.', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, help_text='Short description of attachment')),
                ('size_bytes', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(blank=True, help_text='Optional SHA-256 checksum hex.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_worklog_attachments', to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='worklog.worklog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('status', 'Status highlight'), ('resume', 'Resume bullet')], default='note', max_length=20)),
                ('text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False, help_text='Selected for use in a report/resume/etc.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Optional structured metrics (%, $, latency, etc.).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='worklog.worklog')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('jira', 'Jira'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('linear', 'Linear'), ('asana', 'Asana'), ('other', 'Other')], default='other', max_length=20)),
                ('key', models.CharField(blank=True, help_text='Ticket/issue/PR key (optional).', max_length=120)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='worklog.worklog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('default_work_type', models.CharField(choices=[('delivery', 'Delivery'), ('planning', 'Planning'), ('incident', 'Incident Response'), ('support', 'Support'), ('learning', 'Learning/Training'), ('other', 'Other')], default='delivery', max_length=50)),
                ('default_tags', models.JSONField(blank=True, default=list)),
                ('intake_prompt', models.TextField(blank=True, help_text='Optional prompt/outline the assistant uses to ask questions or structure the entry.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='worklog.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='worklog.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('sprint', 'Sprint'), ('custom', 'Custom')], default='weekly', max_length=20)),
                ('created_via', models.CharField(choices=[('manual', 'Manual'), ('assistant', 'AI Assistant'), ('scheduled', 'Scheduled')], default='assistant', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('content_md', models.TextField(help_text='Markdown content of the report.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='worklog.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='worklog.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='worklog.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogSkillSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('skill', 'Skill'), ('technology', 'Technology'), ('tool', 'Tool'), ('method', 'Method'), ('domain', 'Domain')], default='skill', max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='0.0–1.0 confidence (primarily for AI-suggested signals).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual'), ('import', 'Import')], default='ai', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('evidence', models.TextField(blank=True, help_text='Optional snippet/justification for why this was suggested.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_signals', to='worklog.worklog')),
            ],
            options={
                'ordering': ['-confidence', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'is_active'], name='worklog_cli_user_id_d0bd37_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'name'], name='worklog_cli_user_id_8881bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uq_client_user_name'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['epic', 'is_active'], name='worklog_fea_epic_id_2975ad_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['epic', 'name'], name='worklog_fea_epic_id_323cb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('epic', 'name'), name='uq_feature_epic_name'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'is_active'], name='worklog_pro_client__ff5ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'name'], name='worklog_pro_client__9c410f_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uq_project_client_name'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('started_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='ck_project_dates'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['project', 'is_active'], name='worklog_epi_project_57f988_idx'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['project', 'name'], name='worklog_epi_project_a08baf_idx'),
        ),
        migrations.AddConstraint(
            model_name='epic',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_epic_project_name'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', 'is_active'], name='worklog_spr_project_a3075a_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', '-start_date'], name='worklog_spr_project_d70450_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_sprint_project_name'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ck_sprint_dates'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['feature', 'is_active'], name='worklog_sto_feature_b1cefe_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['feature', 'name'], name='worklog_sto_feature_bbb8c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('feature', 'name'), name='uq_story_feature_name'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['story', 'is_active'], name='worklog_tas_story_i_02b9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['story', 'name'], name='worklog_tas_story_i_5e976b_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('story', 'name'), name='uq_task_story_name'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['user', '-occurred_on'], name='worklog_wor_user_id_6e563e_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['status', '-occurred_on'], name='worklog_wor_status_4e4bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['work_type', '-occurred_on'], name='worklog_wor_work_ty_c2e058_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['client', '-occurred_on'], name='worklog_wor_client__d97970_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['project', '-occurred_on'], name='worklog_wor_project_a748ce_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['enrichment_status'], name='worklog_wor_enrichm_bd3ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['worklog', '-created_at'], name='worklog_att_worklog_ef7e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['kind'], name='worklog_att_kind_cf25a9_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogbullet',
            index=models.Index(fields=['worklog', 'kind'], name='worklog_wor_worklog_f84bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogbullet',
            index=models.Index(fields=['kind', 'is_selected'], name='worklog_wor_kind_fdd963_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogexternallink',
            index=models.Index(fields=['worklog', '-created_at'], name='worklog_wor_worklog_ab38c5_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogexternallink',
            index=models.Index(fields=['system'], name='worklog_wor_system_4be985_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogexternallink',
            index=models.Index(fields=['key'], name='worklog_wor_key_5ddea2_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklogexternallink',
            constraint=models.UniqueConstraint(fields=('worklog', 'url'), name='uq_worklog_external_link_url'),
        ),
        migrations.AddIndex(
            model_name='worklogpreset',
            index=models.Index(fields=['user', 'is_active'], name='worklog_wor_user_id_78750f_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogpreset',
            index=models.Index(fields=['user', 'name'], name='worklog_wor_user_id_ed5c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklogpreset',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uq_worklog_preset_user_name'),
        ),
        migrations.AddIndex(
            model_name='worklogreport',
            index=models.Index(fields=['user', '-created_at'], name='worklog_wor_user_id_29d38f_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogreport',
            index=models.Index(fields=['kind', '-created_at'], name='worklog_wor_kind_c57460_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogreport',
            index=models.Index(fields=['client', '-created_at'], name='worklog_wor_client__42a8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogreport',
            index=models.Index(fields=['project', '-created_at'], name='worklog_wor_project_10117b_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklogreport',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__isnull', True), ('period_start__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='ck_worklog_report_dates'),
        ),
        migrations.AddIndex(
            model_name='worklogskillsignal',
            index=models.Index(fields=['worklog'], name='worklog_wor_worklog_282e15_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogskillsignal',
            index=models.Index(fields=['name'], name='worklog_wor_name_85fb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogskillsignal',
            index=models.Index(fields=['kind'], name='worklog_wor_kind_b69c61_idx'),
        ),
        migrations.AddIndex(
            model_name='worklogskillsignal',
            index=models.Index(fields=['status'], name='worklog_wor_status_c8d795_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklogskillsignal',
            constraint=models.UniqueConstraint(fields=('worklog', 'name', 'kind'), name='uq_worklog_skill_signal'),
        ),
    ]
