# Generated by Django 6.0 on 2025-12-31 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("normalized", models.CharField(max_length=200)),
                ("confidence", models.FloatField(default=0.0)),
                ("level", models.CharField(blank=True, max_length=50, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "normalized"],
            },
        ),
        migrations.CreateModel(
            name="SkillEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.IntegerField()),
                ("excerpt", models.TextField(blank=True)),
                ("weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["user", "-confidence"], name="skills_skil_user_id_26cdee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["normalized"], name="skills_skil_normali_1daef8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("user", "normalized")},
        ),
        migrations.AddIndex(
            model_name="skillevidence",
            index=models.Index(
                fields=["skill", "-created_at"], name="skills_skil_skill_i_926126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillevidence",
            index=models.Index(
                fields=["source_type", "source_id"], name="skills_skil_source__0740d4_idx"
            ),
        ),
    ]
