# Generated by Django 6.0.1 on 2026-01-18 13:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('milestone', 'Milestone'), ('quality', 'Quality'), ('consistency', 'Consistency'), ('special', 'Special')], default='milestone', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('trigger_type', models.CharField(help_text='Type of trigger: streak_7, first_entry, etc', max_length=100)),
                ('trigger_threshold', models.IntegerField(default=0, help_text='Numeric threshold if applicable')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_badge_definition',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(help_text='Type: log_days, attach_evidence, write_outcomes, etc', max_length=100)),
                ('goal_target', models.IntegerField(help_text='Target count to complete', validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('recurrence', models.CharField(default='weekly', help_text='weekly, monthly, etc', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_challenge_template',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_index=True, unique=True)),
                ('config', models.JSONField(help_text='XP rules, caps, thresholds, freeze limits, etc')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gamification_reward_config',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='GamificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_mode', models.BooleanField(default=False, help_text='Reduce/disable gamification UI elements')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('show_xp_details', models.BooleanField(default=True)),
                ('show_challenges', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_settings',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Job ID, trigger details, manual grant reason')),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_badge',
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['user', '-awarded_at'], name='gamificatio_user_id_0e4a2a_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('period_start', models.DateField(help_text='Start of challenge period (e.g., week start)')),
                ('period_end', models.DateField(help_text='End of challenge period')),
                ('current_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Tracking details: dates logged, etc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='gamification.challengetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_challenge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='gamificatio_user_id_a8ef70_idx'), models.Index(fields=['period_end', 'status'], name='gamificatio_period__8e7e60_idx')],
                'unique_together': {('user', 'template', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_counted_date', models.DateField(blank=True, null=True)),
                ('freezes_remaining', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('freezes_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_streak',
                'indexes': [models.Index(fields=['user', '-current_streak'], name='gamificatio_user_id_c45f02_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_xp_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_xp',
                'indexes': [models.Index(fields=['user', '-total_xp'], name='gamificatio_user_id_f6cec6_idx'), models.Index(fields=['-total_xp'], name='gamificatio_total_x_fe2423_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
                ('worklog_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='worklog.worklog')),
            ],
            options={
                'db_table': 'gamification_xp_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_6db20b_idx'), models.Index(fields=['worklog_entry'], name='gamificatio_worklog_3b2cae_idx')],
            },
        ),
    ]
