# Generated by Django 5.2.9 on 2025-12-31 23:08

from django.db import migrations


def load_initial_badges(apps, schema_editor):
    """Load initial badge definitions."""
    BadgeDefinition = apps.get_model('gamification', 'BadgeDefinition')
    
    badges = [
        # Milestone badges
        {
            'code': 'first_entry',
            'name': '🎯 First Step',
            'description': 'Logged your first work entry',
            'category': 'milestone',
            'icon': '🎯',
            'trigger_type': 'first_entry',
            'trigger_threshold': 0,
            'order': 1,
        },
        {
            'code': 'streak_7',
            'name': '🔥 Week Warrior',
            'description': 'Maintained a 7-day logging streak',
            'category': 'consistency',
            'icon': '🔥',
            'trigger_type': 'streak_7',
            'trigger_threshold': 7,
            'order': 10,
        },
        {
            'code': 'streak_30',
            'name': '⚡ Month Master',
            'description': 'Maintained a 30-day logging streak',
            'category': 'consistency',
            'icon': '⚡',
            'trigger_type': 'streak_30',
            'trigger_threshold': 30,
            'order': 11,
        },
        {
            'code': 'streak_100',
            'name': '💎 Century Champion',
            'description': 'Maintained a 100-day logging streak',
            'category': 'consistency',
            'icon': '💎',
            'trigger_type': 'streak_100',
            'trigger_threshold': 100,
            'order': 12,
        },
        {
            'code': 'total_entries_10',
            'name': '📝 Consistent Logger',
            'description': 'Logged 10 work entries',
            'category': 'milestone',
            'icon': '📝',
            'trigger_type': 'total_entries_10',
            'trigger_threshold': 10,
            'order': 20,
        },
        {
            'code': 'total_entries_50',
            'name': '📚 Dedicated Tracker',
            'description': 'Logged 50 work entries',
            'category': 'milestone',
            'icon': '📚',
            'trigger_type': 'total_entries_50',
            'trigger_threshold': 50,
            'order': 21,
        },
        {
            'code': 'total_entries_100',
            'name': '🏆 Century Club',
            'description': 'Logged 100 work entries',
            'category': 'milestone',
            'icon': '🏆',
            'trigger_type': 'total_entries_100',
            'trigger_threshold': 100,
            'order': 22,
        },
        # Quality badges
        {
            'code': 'first_attachment',
            'name': '📎 Evidence Collector',
            'description': 'Added your first attachment',
            'category': 'quality',
            'icon': '📎',
            'trigger_type': 'first_attachment',
            'trigger_threshold': 0,
            'order': 30,
        },
        # Level badges
        {
            'code': 'level_5',
            'name': '🌟 Rising Star',
            'description': 'Reached Level 5',
            'category': 'milestone',
            'icon': '🌟',
            'trigger_type': 'level_5',
            'trigger_threshold': 5,
            'order': 40,
        },
        {
            'code': 'level_10',
            'name': '✨ Expert',
            'description': 'Reached Level 10',
            'category': 'milestone',
            'icon': '✨',
            'trigger_type': 'level_10',
            'trigger_threshold': 10,
            'order': 41,
        },
    ]
    
    for badge_data in badges:
        BadgeDefinition.objects.get_or_create(
            code=badge_data['code'],
            defaults=badge_data
        )


def load_initial_challenges(apps, schema_editor):
    """Load initial challenge templates."""
    ChallengeTemplate = apps.get_model('gamification', 'ChallengeTemplate')
    
    challenges = [
        {
            'code': 'weekly_log_5_days',
            'name': 'Weekly Consistency',
            'description': 'Log work on 5 different days this week',
            'goal_type': 'log_days',
            'goal_target': 5,
            'xp_reward': 50,
            'recurrence': 'weekly',
            'order': 1,
        },
        {
            'code': 'weekly_attach_2',
            'name': 'Evidence Week',
            'description': 'Attach evidence to 2 entries this week',
            'goal_type': 'attach_evidence',
            'goal_target': 2,
            'xp_reward': 30,
            'recurrence': 'weekly',
            'order': 2,
        },
        {
            'code': 'weekly_outcomes_3',
            'name': 'Impact Focus',
            'description': 'Write about outcomes/impact in 3 entries this week',
            'goal_type': 'write_outcomes',
            'goal_target': 3,
            'xp_reward': 40,
            'recurrence': 'weekly',
            'order': 3,
        },
    ]
    
    for challenge_data in challenges:
        ChallengeTemplate.objects.get_or_create(
            code=challenge_data['code'],
            defaults=challenge_data
        )


def load_initial_config(apps, schema_editor):
    """Load default reward configuration."""
    RewardConfig = apps.get_model('gamification', 'RewardConfig')
    
    default_config = {
        'min_entry_length': 20,
        'max_entries_per_hour': 10,
        'duplicate_threshold_seconds': 60,
        'max_daily_xp': 200,
        'xp_rules': {
            'base_entry': 10,
            'per_attachment': 5,
            'per_tag': 3,
            'length_bonus_threshold': 200,
            'length_bonus': 10,
        },
        'max_freezes': 3,
    }
    
    RewardConfig.objects.get_or_create(
        version=1,
        defaults={
            'config': default_config,
            'is_active': True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_badges),
        migrations.RunPython(load_initial_challenges),
        migrations.RunPython(load_initial_config),
    ]
